### ISSUE TITLE
Shtimi i fotove te godinave ne website

### ISSUE THREAD

**Issue by rskikuli** [JoraKasapi/PreservingTirana#11]
Me sa kuptoj për cdo godinë do duhet të ketë nga një foto. Po e hap këtë thread për të vendosur për procesin që do vendoset cdo foto.

**Comment by JoraKasapi** [comment]
Më duhet pak ndihmë për mënyren më të mirë per vendosjen e fotove

**Comment by rskikuli** [comment]
Për mendimin tim skenari ideal do ishte që fotot të publikohen në commons.wikimedia.org dhe link të vendoset në preservingtirana.city. Nga ana tjetër, platforma Commons e Wikimedia është pak e vështirë për tu përdorur për ata që nuk kanë kontribuar më parë :/

**Comment by sidorelauku** [comment]
Kam shtuar opsionin per te vendosur foto, dhe tashme eshte aplikuar ne disa prej ndertesave. Ne momentin qe klikohet ikona, shfaqet edhe imazhi.

**Comment by rskikuli** [comment]
Mund ta mbyllim këtë @JoraKasapi ?

**Comment by JoraKasapi** [comment]
Po, mund te quhet embyllur.
