### ISSUE TITLE
Lidhja e domainit te ri me github-in e projektit

### ISSUE THREAD

**Issue by JoraKasapi** [JoraKasapi/PreservingTirana#12]
Eshtë e nevojshme të bëjmë lidhjen e domainit te ri te blere 'preservingtirana.city' me github-in e projektit ne vend te jorakasapi.com

**Comment by rskikuli** [comment]
Kjo me sa shikoj u bë. Propozoj që të mbyllet issue @JoraKasapi

**Comment by JoraKasapi** [comment]
@sidorelauku  e konfiguroi lidhjen midis domainit dhe faqes ne Github.
