### ISSUE TITLE
Bashkangjitja e linkut me foto nga Wikimedia Commons me Website

### ISSUE THREAD

**Issue by JoraKasapi** [JoraKasapi/PreservingTirana#33]
Duhet gjetur gjithashtu nje menyre qe  tek pjesa e pershkrimit ne te djathte te ndertesave te perfshihet nje link qe te drejton ne Wikimedia Commons dhe ne nje seri fotosh mbi cdo ndertese specifike. @sidorelauku @kominoshja, please.

**Comment by AnXh3L0** [comment]
Nese nuk eshte implementuar ende kjo mund te te ndihmoj.

**Comment by JoraKasapi** [comment]
Hey Anxhelo, e ka bere Sidorela para ca kohesh kete, shume faleminderit qe u ofrove gjithsesi :)
