### ISSUE TITLE
Incorrect link on: Made with <3 by Jora Kasapi.

### ISSUE THREAD

**Issue by xh3n1** [JoraKasapi/PreservingTirana#40]
When you click on "Jora Kasapi", a 404 error is given. Fix the href tag of the link to display the correct website.

**Comment by JoraKasapi** [comment]
Hmm, se kisha vënë re që ka problem. Normalisht duhet të të drejtonte tek websiti im, që momentalisht e kemi lidhur me profilin tim ne Medium.
