### ISSUE TITLE
Website feature: Klikimi ne harte ne nje nga pins te nderteses, te drejtoje ne description-in specifik mbi ate ndertese ne te djathte.

### ISSUE THREAD

**Issue by JoraKasapi** [JoraKasapi/PreservingTirana#50]
Do ishte shume me funksionale po te gjenim nje menyre se si nga klikimi ne harte, ne nje nga pin-s te nderteses, te drejtoje ne description-in specifik mbi ate ndertese ne te djathte, pa pasur nevojen per scroll down deri ne gjetjen e nderteses specifike. @AnXh3L0 po pate nje ide per kete ne te ardhmen :) @sidorelauku gjithashtu.

**Comment by AnXh3L0** [comment]
Cool, po i hedh nje sy Jora :)
